export function isPrimitive(value: unknown): value is Primitive;
export function isDefined<T>(value: T): value is Exclude<T, undefined>;
export function isUndefined<T>(value: T): value is undefined;
export function isDefinedPrimitive(value: unknown): value is DefinedPrimitive;
export function isNonNullable<T>(value: T): value is NonNullable<T>;
export function constant<T>(value: T): T;
export type Defined<T> = Exclude<T, undefined>;
export type DefinedPrimitive = Defined<Primitive>;
export type Primitive = string | boolean | number | symbol | undefined | null | bigint;
export type Nullable = null | undefined;
